#!/bin/sh
TGT='/var/packages/java7'
if [ ! -e $TGT ]; then
	echo "Java 7 package isn't installed. Please install this package first before installing this package." >  $SYNOPKG_TEMP_LOGFILE
	exit 1
fi
exit 0 
