#!/bin/sh
jettyversion=`jetty-distribution-9.0.2.v20130417`
packagepath=`/var/packages/jetty/target/`
tar -xvf ${packagepath}${jettyversion}.tar.gz
mv -f ${packagepath}jetty-deploy.xml ${packagepath}${jettyversion}/etc/jetty-deploy.xml 
mv -f ${packagepath}jetty-logging.xml ${packagepath}${jettyversion}/etc/jetty-logging.xml 
synoshare --add webapps "" /volume1/webapps "" "@administrators" "" 1 0
exit 0 
